import Link from 'next/link';
import { Footer } from '@/components/Footer';

export const metadata = { title: 'Terms of Use — TrialMatch AI' };

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <nav className="border-b border-gray-100 bg-white sticky top-0 z-10">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 h-14 flex items-center gap-2">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-7 h-7 rounded-lg bg-blue-600 flex items-center justify-center">
              <svg className="w-4 h-4 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M9.75 3.104v5.714a2.25 2.25 0 01-.659 1.591L5 14.5M9.75 3.104c-.251.023-.501.05-.75.082m.75-.082a24.301 24.301 0 014.5 0m0 0v5.714c0 .597.237 1.17.659 1.591L19.8 15.3M14.25 3.104c.251.023.501.05.75.082M19.8 15.3l-1.57.393A9.065 9.065 0 0112 15a9.065 9.065 0 00-6.23-.693L5 14.5m14.8.8l1.402 1.402c1.232 1.232.65 3.318-1.067 3.611A48.309 48.309 0 0112 21c-2.773 0-5.491-.235-8.135-.687-1.718-.293-2.3-2.379-1.067-3.61L5 14.5" />
              </svg>
            </div>
            <span className="font-bold text-gray-900 text-sm">TrialMatch AI</span>
          </Link>
        </div>
      </nav>

      <main className="max-w-3xl mx-auto px-4 sm:px-6 py-12">
        <div className="mb-8">
          <Link href="/" className="inline-flex items-center gap-1.5 text-sm text-gray-400 hover:text-gray-700 mb-6 transition-colors">
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M10.5 19.5L3 12m0 0l7.5-7.5M3 12h18" />
            </svg>
            Back to home
          </Link>
          <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms of Use</h1>
          <p className="text-sm text-gray-400">Last updated: May 2, 2026</p>
        </div>

        <div className="space-y-8 text-gray-700">
          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">Acceptance of Terms</h2>
            <p className="text-sm leading-relaxed">
              By accessing or using TrialMatch AI, you agree to these Terms of Use. If you do not agree,
              please do not use this service. TrialMatch AI is a hackathon demonstration project and is
              provided as-is for educational and informational purposes.
            </p>
          </section>

          <section id="disclaimer">
            <h2 className="text-lg font-semibold text-gray-900 mb-3">Medical Disclaimer</h2>
            <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 mb-4">
              <p className="text-sm text-amber-800 font-medium leading-relaxed">
                TrialMatch AI is not a medical device, and the information it provides does not constitute
                medical advice, diagnosis, or treatment recommendations.
              </p>
            </div>
            <p className="text-sm leading-relaxed mb-3">
              Trial matches and eligibility explanations are generated by AI and may be inaccurate, incomplete,
              or outdated. Clinical trial eligibility is a complex medical determination that must be made
              by qualified healthcare professionals.
            </p>
            <p className="text-sm leading-relaxed">
              Always consult your physician, oncologist, or relevant specialist before considering enrollment
              in any clinical trial. Do not make any medical decisions based solely on information provided
              by this tool.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">Use of the Service</h2>
            <p className="text-sm leading-relaxed mb-3">You agree to use TrialMatch AI only for lawful purposes. You must not:</p>
            <ul className="text-sm space-y-2 list-disc list-inside text-gray-600">
              <li>Input false, misleading, or third-party personal data without consent</li>
              <li>Attempt to reverse-engineer, scrape, or overload the service</li>
              <li>Use the service for any commercial purpose without permission</li>
              <li>Rely on the service as a substitute for professional medical advice</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">Data Accuracy</h2>
            <p className="text-sm leading-relaxed">
              Clinical trial data is sourced from ClinicalTrials.gov and was last fetched at build time.
              Trial status, eligibility criteria, and contact information may have changed. Always verify
              trial details directly on{' '}
              <a
                href="https://clinicaltrials.gov"
                target="_blank"
                rel="noopener noreferrer"
                className="text-blue-600 hover:underline"
              >
                ClinicalTrials.gov
              </a>{' '}
              or with the study site before taking any action.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">Limitation of Liability</h2>
            <p className="text-sm leading-relaxed">
              TrialMatch AI and its developers are not liable for any damages arising from your use of,
              or inability to use, this service. This includes but is not limited to any harm resulting
              from reliance on AI-generated eligibility assessments or trial information.
              The service is provided "as is" without warranties of any kind.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">Intellectual Property</h2>
            <p className="text-sm leading-relaxed">
              The TrialMatch AI interface, code, and branding are the property of the BeaverHacks team.
              Clinical trial data is public domain content sourced from ClinicalTrials.gov (U.S. National Library of Medicine).
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">Changes to These Terms</h2>
            <p className="text-sm leading-relaxed">
              We may update these terms at any time. Continued use of the service after changes constitutes
              acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">Contact</h2>
            <p className="text-sm leading-relaxed">
              Questions about these terms? Reach out via the{' '}
              <a
                href="https://github.com/amanshaman11/hackathon-project"
                target="_blank"
                rel="noopener noreferrer"
                className="text-blue-600 hover:underline"
              >
                project repository
              </a>.
            </p>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  );
}
