export type CountryOption = { label: string; value: string };

export const COUNTRIES: CountryOption[] = [
  { label: 'All Countries', value: '' },
  { label: 'United States', value: 'United States' },
  { label: 'Canada', value: 'Canada' },
  { label: 'United Kingdom', value: 'United Kingdom' },
  { label: 'Australia', value: 'Australia' },
  { label: 'New Zealand', value: 'New Zealand' },
  { label: 'Germany', value: 'Germany' },
  { label: 'France', value: 'France' },
  { label: 'Italy', value: 'Italy' },
  { label: 'Spain', value: 'Spain' },
  { label: 'Netherlands', value: 'Netherlands' },
  { label: 'Belgium', value: 'Belgium' },
  { label: 'Switzerland', value: 'Switzerland' },
  { label: 'Austria', value: 'Austria' },
  { label: 'Sweden', value: 'Sweden' },
  { label: 'Denmark', value: 'Denmark' },
  { label: 'Norway', value: 'Norway' },
  { label: 'Finland', value: 'Finland' },
  { label: 'Poland', value: 'Poland' },
  { label: 'Czech Republic', value: 'Czechia' },
  { label: 'Hungary', value: 'Hungary' },
  { label: 'Romania', value: 'Romania' },
  { label: 'Israel', value: 'Israel' },
  { label: 'Turkey', value: 'Turkey' },
  { label: 'Russia', value: 'Russian Federation' },
  { label: 'Japan', value: 'Japan' },
  { label: 'China', value: 'China' },
  { label: 'South Korea', value: 'Korea, Republic of' },
  { label: 'Taiwan', value: 'Taiwan' },
  { label: 'Singapore', value: 'Singapore' },
  { label: 'Hong Kong', value: 'Hong Kong' },
  { label: 'Thailand', value: 'Thailand' },
  { label: 'Malaysia', value: 'Malaysia' },
  { label: 'India', value: 'India' },
  { label: 'Brazil', value: 'Brazil' },
  { label: 'Mexico', value: 'Mexico' },
  { label: 'Argentina', value: 'Argentina' },
  { label: 'Colombia', value: 'Colombia' },
  { label: 'Chile', value: 'Chile' },
  { label: 'South Africa', value: 'South Africa' },
  { label: 'Egypt', value: 'Egypt' },
];
