import type { Trial } from '@/lib/types';

export const MOCK_TRIALS: Trial[] = [
  {
    nctId: 'NCT-LUNG-001',
    title: 'Pembrolizumab + Docetaxel for Stage III NSCLC',
    conditions: ['non-small cell lung cancer', 'lung cancer'],
    briefSummary: 'This trial studies a combination immunotherapy and chemotherapy plan for advanced non-small cell lung cancer.',
    eligibilityCriteria:
      'Adults age 18-75 with non-small cell lung cancer. Prior chemotherapy allowed.',
    minAge: 18,
    maxAge: 75,
    sex: 'ALL',
    status: 'RECRUITING',
    phases: ['Phase 2'],
    locations: [
      { facility: 'OHSU Cancer Center', city: 'Portland', state: 'OR', country: 'USA' },
    ],
    url: 'https://clinicaltrials.gov/study/NCT-LUNG-001',
  },
  {
    nctId: 'NCT-DIAB-101',
    title: 'Metabolic Outcomes in Type 2 Diabetes on GLP-1 Therapy',
    conditions: ['type 2 diabetes', 'diabetes'],
    briefSummary: 'Evaluates blood sugar and weight outcomes in adults with Type 2 diabetes using GLP-1 medications.',
    eligibilityCriteria: 'Adults age 30-70 with diagnosed Type 2 diabetes.',
    minAge: 30,
    maxAge: 70,
    sex: 'ALL',
    status: 'RECRUITING',
    phases: ['Phase 3'],
    locations: [
      { facility: 'UCLA Medical Center', city: 'Los Angeles', state: 'CA', country: 'USA' },
    ],
    url: 'https://clinicaltrials.gov/study/NCT-DIAB-101',
  },
  {
    nctId: 'NCT-BRCA-210',
    title: 'Hormone-Directed Therapy After Mastectomy',
    conditions: ['breast cancer'],
    briefSummary: 'Compares outcomes after surgery using different hormone-directed maintenance therapies.',
    eligibilityCriteria: 'Adults age 35-80 with prior surgery for breast cancer.',
    minAge: 35,
    maxAge: 80,
    sex: 'FEMALE',
    status: 'RECRUITING',
    phases: ['Phase 2'],
    locations: [
      { facility: 'Seattle Cancer Care Alliance', city: 'Seattle', state: 'WA', country: 'USA' },
    ],
    url: 'https://clinicaltrials.gov/study/NCT-BRCA-210',
  },
  {
    nctId: 'NCT-ASTH-315',
    title: 'New Biologic Therapy for Severe Asthma',
    conditions: ['asthma'],
    briefSummary: 'Tests a biologic drug in adults with moderate to severe persistent asthma symptoms.',
    eligibilityCriteria: 'Adults age 18-65 with persistent asthma despite inhaler therapy.',
    minAge: 18,
    maxAge: 65,
    sex: 'ALL',
    status: 'RECRUITING',
    phases: ['Phase 2'],
    locations: [
      { facility: 'Stanford Pulmonary Clinic', city: 'Palo Alto', state: 'CA', country: 'USA' },
    ],
    url: 'https://clinicaltrials.gov/study/NCT-ASTH-315',
  },
  {
    nctId: 'NCT-HF-411',
    title: 'Heart Failure Remote Monitoring and Medication Adjustment',
    conditions: ['heart failure'],
    briefSummary: 'Evaluates whether remote monitoring improves outcomes in chronic heart failure care.',
    eligibilityCriteria: 'Adults age 40-85 with diagnosed chronic heart failure.',
    minAge: 40,
    maxAge: 85,
    sex: 'ALL',
    status: 'RECRUITING',
    phases: ['Phase 4'],
    locations: [
      { facility: 'Mayo Clinic', city: 'Rochester', state: 'MN', country: 'USA' },
    ],
    url: 'https://clinicaltrials.gov/study/NCT-HF-411',
  },
];
